### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yanxiatao** [ixiaohei-sakura/blh-blivedm#1]
Traceback (most recent call last):
  File "/root/mcdr/utils/plugin.py", line 68, in run
    super().run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "plugins/BlhSocketClient.py", line 113, in on_info
    s.sendall(bytes(info.content, encoding='utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
请问出现这个问题要怎么解决

**Comment by ixiaohei-sakura** [comment]
进程管道的问题
这个项目要暂时咕一阵子
但是我会尽快处理的

**Comment by ixiaohei-sakura** [comment]
会把多进程部分换掉，改成协程或多线程
之前开发的时候刚接触python没多久，不怎么会用协程和多线程XD
这个问题好多人都出现了，就是进程管理的问题

**Comment by ixiaohei-sakura** [comment]
大换血已经完成
